-- METATILE CENSUS, keyed by the tileset that OWNS the metatile.
-- Gen 3 splits the id space: 0..inPrimary-1 come from the map's PRIMARY
-- tileset and the rest from its SECONDARY.  Hoenn has three primaries and
-- seventy secondaries, so keying by the pair (75 combinations) counted the
-- same General-tileset cliff seventy-five times.  Keyed by owner, every
-- outdoor map's terrain collapses onto one table of at most inPrimary rows.
--
-- THE SPLIT IS NOT A CONSTANT ACROSS CARTRIDGES.  It is 512 on Emerald and
-- 640 on FireRed (stated: lib/Gen3.lua inPrimary(), which reads the cache's
-- own constants.gen3Layout.metatilesInPrimary), so this asks rather than
-- hardcodes -- a FireRed run with 512 baked in mis-owns every metatile in
-- 512..639, which is the whole of that cartridge's primary tail.
--
--   VERSION=firered ENGINE=<tree> OUT=<out>.lua luajit tools/gen3_census.lua
--
-- See tools/gen3_harness.lua for the environment and for how layoutnames was
-- reconstructed after the scratch file it used to be dofile'd from was lost.
local H = dofile((os.getenv("SHAPEMOD") or ((os.getenv("ENGINE") or "/tmp/fr")
  .. "/mods/DRAMATIC_SHAPE")):gsub("/*$", "/") .. "tools/gen3_harness.lua")
local tilesets, layouts = H.tilesets, H.layouts
local g3maps, layIdxByName = H.g3maps, H.layIdxByName
local Map, Gen3 = H.Map, H.Gen3
local IN_PRIMARY = H.inPrimary

-- THE PAIR KEY, PICKED THE SAME WAY TWICE.  This returned whichever key
-- `pairs(tilesets)` happened to yield first, and a layout with no secondary
-- matches every pair sharing its primary, so the census could differ between
-- two runs over the same cache.  Collect the matches and take the lowest in
-- ASCII order -- the same rule gen3_metatiles_gen.lua settled on.
local function pairKeyFor(l)
  local function hex(a) return a and ("%07X"):format(a) or nil end
  local p,s=hex(l.primaryTileset),hex(l.secondaryTileset)
  local hit={}
  for id in pairs(tilesets) do if type(id)=="string" and p and id:find(p,1,true) then
    if s==nil or id:find(s,1,true) then hit[#hit+1]=id end end end
  table.sort(hit)
  return hit[1]
end
local acc = {}
local function slot(key, m)
  local t=acc[key] if not t then t={} acc[key]=t end
  local e=t[m]
  if not e then e={n=0,beh=nil,layer=nil,coll={},elev={},nmaps=0,maps={},
                   up={},down={},left={},right={},pairs_={}} t[m]=e end
  return e
end
local nmap=0
for id,ent in pairs(g3maps.maps or {}) do
  local li=layIdxByName[ent.layout]
  local lay=li and layouts[li]
  if lay and lay.blocks and lay.width and lay.height then
    local key=pairKeyFor(lay)
    if key and tilesets[key] then
      local pkey=("P%07X"):format(lay.primaryTileset or 0)
      local skey=("S%07X"):format(lay.secondaryTileset or 0)
      local def={id=id,width=lay.width,height=lay.height,blocks=lay.blocks,
        collisionCells=lay.collisionCells,elevationCells=lay.elevationCells,
        border=lay.border,
        borderBlock=lay.border and (lay.border:byte(1)+lay.border:byte(2)*256)%1024 or 0,
        tileset=key}
      local ok,map=pcall(Map.new,def,tilesets[key])
      if ok and map then
        map.id=id
        local okc,ctx=pcall(Gen3.forMap,map)
        if okc and ctx then
          nmap=nmap+1
          local W,H2=lay.width,lay.height
          local function mt(cx,cy)
            if cx<0 or cy<0 or cx>=W or cy>=H2 then return nil end
            return ctx.metatileAt(cx,cy)
          end
          for cy=0,H2-1 do for cx=0,W-1 do
            local i=cy*W+cx+1
            local m=mt(cx,cy)
            if m then
              local e=slot(m<IN_PRIMARY and pkey or skey, m)
              e.n=e.n+1
              if not e.maps[ent.name] then e.maps[ent.name]=0 e.nmaps=e.nmaps+1 end
              e.maps[ent.name]=e.maps[ent.name]+1
              e.pairs_[key]=true
              if e.beh==nil then local b,l=ctx.attributes(m) e.beh,e.layer=b,l end
              local c=(lay.collisionCells and lay.collisionCells[i]) or 0
              local z=(lay.elevationCells and lay.elevationCells[i]) or 0
              e.coll[c]=(e.coll[c] or 0)+1
              e.elev[z]=(e.elev[z] or 0)+1
              local u,d,l2,r=mt(cx,cy-1),mt(cx,cy+1),mt(cx-1,cy),mt(cx+1,cy)
              if u then e.up[u]=(e.up[u] or 0)+1 end
              if d then e.down[d]=(e.down[d] or 0)+1 end
              if l2 then e.left[l2]=(e.left[l2] or 0)+1 end
              if r then e.right[r]=(e.right[r] or 0)+1 end
            end
          end end
        end
      end
    end
  end
end
local out=io.open(os.getenv("OUT") or "/tmp/t/census_owned.lua","w")
out:write("-- generated by /tmp/t/mkcensus.lua -- do not hand-edit\nreturn {\n")
local keys={} for k in pairs(acc) do keys[#keys+1]=k end table.sort(keys)
local total=0
for _,k in ipairs(keys) do
  local t=acc[k]
  local ms={} for m in pairs(t) do ms[#ms+1]=m end table.sort(ms)
  total=total+#ms
  out:write(("  [%q] = {\n"):format(k))
  for _,m in ipairs(ms) do
    local e=t[m]
    local function top(tab,lim)
      local a={} for kk,v in pairs(tab) do a[#a+1]={kk,v} end
      table.sort(a,function(x,y) if x[2]~=y[2] then return x[2]>y[2] end return x[1]<y[1] end)
      local s={} for i=1,math.min(lim or 4,#a) do s[#s+1]=("%d:%d"):format(a[i][1],a[i][2]) end
      return table.concat(s,",")
    end
    local np=0 for _ in pairs(e.pairs_) do np=np+1 end
    out:write(("    [%d]={n=%d,beh=%d,layer=%d,nmaps=%d,npairs=%d,coll=%q,elev=%q,up=%q,down=%q,left=%q,right=%q},\n")
      :format(m,e.n,e.beh or 0,e.layer or 0,e.nmaps,np,top(e.coll,4),top(e.elev,4),
              top(e.up,4),top(e.down,4),top(e.left,4),top(e.right,4)))
  end
  out:write("  },\n")
end
out:write("}\n") out:close()
io.stderr:write(("version=%s maps=%d owners=%d rows=%d inPrimary=%d\n")
  :format(H.VERSION,nmap,#keys,total,IN_PRIMARY))
